In [155]:
# Logistic regression is a fundamental supervised machine learning algorithm used for classification,
#  predicting the probability of a binary outcome (e.g., yes/no, 0/1) based on independent variables

In [156]:
import pandas as pd
data=pd.read_csv("student_data.csv")
data

     student_id  gender  age  ... previous_gpa pass_fail grade_category
0        S00001    Male   17  ...         2.44      Fail              F
1        S00002  Female   18  ...         2.79      Pass              C
2        S00003    Male   17  ...         1.49      Fail              F
3        S00004    Male   18  ...         1.34      Fail              F
4        S00005    Male   18  ...         2.60      Pass              C
...         ...     ...  ...  ...          ...       ...            ...
9995     S09996  Female   15  ...         1.54      Fail              F
9996     S09997    Male   15  ...         1.49      Fail              F
9997     S09998  Female   15  ...         2.38      Pass              D
9998     S09999  Female   18  ...         1.45      Fail              F
9999     S10000    Male   17  ...         2.24      Pass              D

[10000 rows x 23 columns]

In [157]:
data.drop("student_id", axis=1,inplace=True)

In [158]:

data.drop("family_income", axis=1,inplace=True)

In [159]:
data.grade_category.value_counts()

grade_category
F    5172
D    3829
C     904
B      85
A      10
Name: count, dtype: int64

In [160]:
from sklearn.preprocessing import LabelEncoder
# used in place of "map" to manupulate data like yes:1 no:0
encoder=LabelEncoder()

In [161]:
encoder

LabelEncoder()

In [162]:
data.grade_category=encoder.fit_transform(data.grade_category)

In [163]:
data.pass_fail=encoder.fit_transform(data.pass_fail)

In [164]:
data.tutoring=encoder.fit_transform(data.tutoring)

In [165]:
data.study_environment=encoder.fit_transform(data.study_environment)

In [166]:
data.parental_education=encoder.fit_transform(data.parental_education)

In [167]:
data.internet_access=encoder.fit_transform(data.internet_access)

In [168]:
data.gender=encoder.fit_transform(data.gender)

In [169]:
data.head()

   gender  age  parental_education  ...  previous_gpa  pass_fail  grade_category
0       1   17                   1  ...          2.44          0               4
1       0   18                   1  ...          2.79          1               2
2       1   17                   1  ...          1.49          0               4
3       1   18                   0  ...          1.34          0               4
4       1   18                   0  ...          2.60          1               2

[5 rows x 21 columns]

In [170]:
x=data.drop("grade_category",axis=1)
y=data.grade_category

In [171]:
x.head()

   gender  age  parental_education  ...  final_exam_score  previous_gpa  pass_fail
0       1   17                   1  ...              49.1          2.44          0
1       0   18                   1  ...              70.1          2.79          1
2       1   17                   1  ...              42.2          1.49          0
3       1   18                   0  ...              31.9          1.34          0
4       1   18                   0  ...              66.4          2.60          1

[5 rows x 20 columns]

In [172]:
y.head()

0    4
1    2
2    4
3    4
4    2
Name: grade_category, dtype: int64

In [173]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=10)

In [174]:
x_train

      gender  age  ...  previous_gpa  pass_fail
5663       1   17  ...          1.30          0
2840       1   16  ...          2.32          1
4550       0   16  ...          0.94          0
17         0   17  ...          2.11          0
3442       1   15  ...          2.19          1
...      ...  ...  ...           ...        ...
9372       0   16  ...          1.26          0
7291       1   18  ...          1.93          0
1344       1   15  ...          2.52          1
7293       0   18  ...          1.81          0
1289       1   17  ...          1.84          1

[7000 rows x 20 columns]

In [175]:
x_test

      gender  age  ...  previous_gpa  pass_fail
937        1   15  ...          1.12          0
9355       1   17  ...          2.16          1
2293       0   16  ...          2.06          0
192        1   15  ...          2.24          1
8675       0   16  ...          2.17          0
...      ...  ...  ...           ...        ...
4964       0   18  ...          1.23          0
8978       0   18  ...          1.21          0
7540       1   15  ...          1.79          0
5275       1   15  ...          2.73          1
9654       0   18  ...          1.71          0

[3000 rows x 20 columns]

In [176]:
y_train

5663    4
2840    3
4550    4
17      4
3442    3
       ..
9372    4
7291    4
1344    3
7293    4
1289    3
Name: grade_category, Length: 7000, dtype: int64

In [177]:
y_test

937     4
9355    2
2293    4
192     3
8675    4
       ..
4964    4
8978    4
7540    4
5275    3
9654    4
Name: grade_category, Length: 3000, dtype: int64

In [178]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

In [179]:
model

LogisticRegression()

In [180]:
model.fit(x_train,y_train)

c:\Users\arshd\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [181]:
y_pred=model.predict(x_test)
y_pred

array([4, 3, 4, ..., 4, 3, 4], shape=(3000,))

In [186]:
from sklearn.metrics import r2_score ,mean_squared_error
r2_score(y_test,y_pred)

0.7932840436785729

In [183]:
mean_squared_error(y_pred,y_test)

0.09933333333333333